[program:backend-proxy]
command=/usr/sbin/nginx -g "daemon off;" -c /etc/nginx/nginx-backend-proxy.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/backend-proxy.err.log
stdout_logfile=/var/log/supervisor/backend-proxy.out.log
priority=4
startsecs=2
stopwaitsecs=10
